const subdomainDictionary = {
    'tech.slashdot.org': 'Slashdot',
    'bbc.co.uk': 'BBC',
    'uk.reuters.com': 'Reuters',
    'hardware.slashdot.org': 'Slashdot',
    'yro.slashdot.org': 'Slashdot',
    'it.slashdot.org': 'Slashdot',
  };
  
  // Base domain to source mapping
  const sourceDictionary = {
    mvvariety: 'Marianas Variety',
    muckrock: 'Muckrock',
    foxnews: 'Fox News',
    kilkennypeople: 'kilkennylive',
    nationalreview: 'National Review',
    independent: 'Irish Independent',
    voanews: 'VOA',
    mainichi: 'The Mainichi',
    aa: 'AA',
    cbsnews: 'CBS',
    australianmining: 'Australian Mining',
    cnbc: 'CNBC',
    espn: 'ESPN',
    wbaltv: 'WBAL-TV',
    news18: 'NEWS18',
    abc7ny: 'abc7NY',
    bigoven: 'BigOven',
    wlwt: 'WLWT',
    dailymail: 'DailyMail',
    dnaindia: 'DNA India',
    galvnews: 'GalvNews',
    theglobeandmail: 'The Globe and Mail',
    'business-standard': 'Business Standard',
    scmp: 'South China Morning Post',
    nytimes: 'The New York Times',
    abcnews: 'abcNews',
    dw: 'DW',
    channelnewsasia: 'cna',
    thewest: 'The West Australian',
    washingtonpost: 'The Washinton Post',
    breakingdefense: 'Breaking Defense',
    seekingalpha: 'Seeking Alpha',
    tmz: 'TMZ',
    venturebeat: 'Venture Beat',
    bernama: 'BERNAMA',
    koreatimes: 'Korea Times',
    news4jax: 'News4Jax',
    clickondetroit: 'Click On Detroit',
    npr: 'NPR',
    denverpost: 'The Denver Post',
    ndtv: 'NDTV',
    indiatoday: 'India Today',
    nature: 'nature nedicine',
    washingtontimes: 'The Washington Times',
    theguardian: 'The Guardian',
    ign: 'IGN',
    yankodesign: 'Yanko Design',
    upi: 'UPI',
    phys: 'Phys Org'
  };

module.exports = {
    subdomainDictionary,
    sourceDictionary,
};